import { MemoryBookTemplate } from '../types/memory-book.types';

export const OFFICIAL_MEMORY_BOOK_TEMPLATE_10_PAGES: MemoryBookTemplate = {
  id: 'cahier_10_pages_marketing_v1',
  title: 'Mon cahier de souvenirs',
  subtitle: 'Mes petits moments, mes grandes histoires ✨',
  description: 'Le modèle officiel 10 pages Petit Baobab inspiré de la savane pour immortaliser tous les moments précieux de ton enfance.',
  coverBadge: 'Modèle Officiel 10 Pages',
  icon: 'BookOpen',
  previewThumbnail: '/cahier-souvenirs/cover.png',
  totalDefaultPages: 10,
  pages: [
    // Page 1: Ma couverture
    {
      id: 'cover',
      pageNumber: 1,
      templateId: 'cover-v1',
      title: 'Ma couverture',
      subtitle: 'Mon cahier de souvenirs',
      categoryTag: 'Couverture',
      headerIcon: 'BookOpen',
      backgroundTheme: 'warm-cream',
      status: 'complete',
      data: {
        title: 'Mon cahier de souvenirs',
        subtitle: 'Mes petits moments, mes grandes histoires ✨',
        childName: 'Aminata',
        schoolYear: '2025 - 2026',
        coverImage: '/cahier-souvenirs/cover.png',
      },
      elements: [
        {
          id: 'cover_title',
          type: 'text',
          title: 'Titre du cahier',
          textData: { value: 'Mon cahier de souvenirs' },
        },
        {
          id: 'cover_child_name',
          type: 'text',
          title: 'Prénom de l’enfant',
          textData: { value: 'Aminata' },
        },
        {
          id: 'cover_year',
          type: 'text',
          title: 'Année scolaire',
          textData: { value: '2025 - 2026' },
        },
      ],
    },

    // Page 2: Mon portrait (Prototype fidélité 100%)
    {
      id: 'portrait',
      pageNumber: 2,
      templateId: 'portrait-v1',
      title: 'Mon portrait',
      subtitle: 'Tout sur moi cette année',
      categoryTag: 'Portrait',
      headerIcon: 'Palette',
      backgroundTheme: 'warm-cream',
      status: 'complete',
      data: {
        name: 'Aminata',
        birthday: '12 / 05 / 2018',
        age: '6 ans',
        height: '120 cm',
        favoriteColor: '#7658e8',
        favoriteFood: 'Le riz au poulet',
        favoriteAnimal: 'Le lion',
        futureDream: 'Je veux être médecin pour aider les autres.',
        dreamCatch: 'Rêve\nGrand !',
        love: 'Jouer avec mes amis,\nles gâteaux et les dessins.',
        hate: 'Les légumes\net me lever tôt.',
        photoUrl: '/cahier-souvenirs/child.png',
        zoom: 1,
        rotation: 0,
        offsetX: 0,
        offsetY: 0,
      },
      elements: [
        {
          id: 'portrait_photo',
          type: 'photo',
          title: 'Photo de portrait',
          photoData: {
            url: '/cahier-souvenirs/child.png',
            zoom: 1,
            rotation: 0,
            offsetX: 0,
            offsetY: 0,
          },
        },
        {
          id: 'portrait_name',
          type: 'text',
          title: 'Mon prénom',
          textData: { value: 'Aminata' },
        },
        {
          id: 'portrait_birthday',
          type: 'text',
          title: 'Mon anniversaire',
          textData: { value: '12 / 05 / 2018' },
        },
        {
          id: 'portrait_age',
          type: 'text',
          title: 'Mon âge',
          textData: { value: '6 ans' },
        },
        {
          id: 'portrait_height',
          type: 'text',
          title: 'Ma taille',
          textData: { value: '120 cm' },
        },
        {
          id: 'portrait_color',
          type: 'choice',
          title: 'Ma couleur préférée',
          choiceData: {
            selectedId: '#7658e8',
            options: [
              { id: '#36a96b', label: 'Vert' },
              { id: '#2aa5dc', label: 'Bleu ciel' },
              { id: '#ffc83d', label: 'Jaune' },
              { id: '#f28b30', label: 'Orange' },
              { id: '#f58b9b', label: 'Rose' },
              { id: '#7658e8', label: 'Violet' },
            ],
          },
        },
        {
          id: 'portrait_food',
          type: 'text',
          title: 'Mon plat préféré',
          textData: { value: 'Le riz au poulet' },
        },
        {
          id: 'portrait_animal',
          type: 'text',
          title: 'Mon animal préféré',
          textData: { value: 'Le lion' },
        },
        {
          id: 'portrait_dream',
          type: 'text',
          title: 'Plus tard, je serai',
          textData: { value: 'Je veux être médecin pour aider les autres.' },
        },
        {
          id: 'portrait_love',
          type: 'text',
          title: 'J’adore',
          textData: { value: 'Jouer avec mes amis,\nles gâteaux et les dessins.' },
        },
        {
          id: 'portrait_hate',
          type: 'text',
          title: 'Je déteste',
          textData: { value: 'Les légumes\net me lever tôt.' },
        },
      ],
    },

    // Page 3: Mon année
    {
      id: 'year',
      pageNumber: 3,
      templateId: 'year-v1',
      title: 'Mon année',
      subtitle: 'Mon école et ma classe',
      categoryTag: 'École',
      headerIcon: 'School',
      backgroundTheme: 'warm-cream',
      status: 'draft',
      data: {
        schoolName: 'École Les Petits Baobabs',
        grade: 'Grande Section / CP',
        teacherName: 'Mme Awa',
        favoriteSubject: 'Le dessin et les histoires',
        recessGame: 'La marelle et le ballon',
        bestMemory: 'Le jour du spectacle de fin d’année !',
        photoUrl: '/cahier-souvenirs/child.png',
        zoom: 1,
        rotation: 0,
      },
      elements: [
        {
          id: 'year_school',
          type: 'text',
          title: 'Mon école',
          textData: { value: 'École Les Petits Baobabs' },
        },
        {
          id: 'year_grade',
          type: 'text',
          title: 'Ma classe',
          textData: { value: 'Grande Section / CP' },
        },
        {
          id: 'year_teacher',
          type: 'text',
          title: 'Mon maître / ma maîtresse',
          textData: { value: 'Mme Awa' },
        },
      ],
    },

    // Page 4: Mes camarades
    {
      id: 'friends',
      pageNumber: 4,
      templateId: 'friends-v1',
      title: 'Mes camarades',
      subtitle: 'Mes meilleurs copains et copines',
      categoryTag: 'Amitié',
      headerIcon: 'Users',
      backgroundTheme: 'warm-cream',
      status: 'draft',
      data: {
        bestFriends: 'Fatou, Moussa, Lucas et Sarah',
        gamesTogether: 'Inventer des histoires et courir dans la cour',
        funnyMoments: 'Quand on a tous rigolé à la cantine !',
        photoUrl: '/cahier-souvenirs/child.png',
        zoom: 1,
        rotation: 0,
      },
      elements: [
        {
          id: 'friends_names',
          type: 'text',
          title: 'Mes meilleurs amis',
          textData: { value: 'Fatou, Moussa, Lucas et Sarah' },
        },
      ],
    },

    // Page 5: Mes souvenirs
    {
      id: 'memories',
      pageNumber: 5,
      templateId: 'memories-v1',
      title: 'Mes souvenirs',
      subtitle: 'Les moments inoubliables',
      categoryTag: 'Moments',
      headerIcon: 'Star',
      backgroundTheme: 'warm-cream',
      status: 'draft',
      data: {
        memory1Title: 'La sortie au zoo',
        memory1Text: 'J’ai vu des girafes et des éléphants immenses !',
        memory2Title: 'Mon anniversaire',
        memory2Text: 'Un magnifique gâteau au chocolat et tous mes amis réunis.',
        photoUrl: '/cahier-souvenirs/child.png',
        zoom: 1,
        rotation: 0,
      },
      elements: [],
    },

    // Page 6: Mes livres
    {
      id: 'books',
      pageNumber: 6,
      templateId: 'books-v1',
      title: 'Mes livres',
      subtitle: 'Mes lectures et histoires favorites',
      categoryTag: 'Lectures',
      headerIcon: 'Book',
      backgroundTheme: 'warm-cream',
      status: 'draft',
      data: {
        favoriteBook: 'Le Secret du Grand Baobab',
        favoriteHero: 'Kaya la petite lionne',
        storyMoral: 'L’amitié est le plus beau trésor.',
        photoUrl: '/cahier-souvenirs/child.png',
        zoom: 1,
        rotation: 0,
      },
      elements: [],
    },

    // Page 7: Mes fiertés
    {
      id: 'pride',
      pageNumber: 7,
      templateId: 'pride-v1',
      title: 'Mes fiertés',
      subtitle: 'Ce que j’ai réussi cette année',
      categoryTag: 'Victoires',
      headerIcon: 'Award',
      backgroundTheme: 'warm-cream',
      status: 'draft',
      data: {
        proud1: 'J’ai appris à faire du vélo sans les petites roues !',
        proud2: 'Je sais écrire mon prénom tout seul.',
        proud3: 'J’aide mes amis quand ils ont besoin.',
        photoUrl: '/cahier-souvenirs/child.png',
        zoom: 1,
        rotation: 0,
      },
      elements: [],
    },

    // Page 8: Mes vacances
    {
      id: 'vacation',
      pageNumber: 8,
      templateId: 'vacation-v1',
      title: 'Mes vacances',
      subtitle: 'Aventures et découvertes',
      categoryTag: 'Voyages',
      headerIcon: 'Sun',
      backgroundTheme: 'warm-cream',
      status: 'draft',
      data: {
        destination: 'Chez mes grands-parents au village',
        activities: 'Baignade, cueillir des mangues et regarder les étoiles',
        specialMemory: 'Les histoires racontées le soir au coin du feu.',
        photoUrl: '/cahier-souvenirs/child.png',
        zoom: 1,
        rotation: 0,
      },
      elements: [],
    },

    // Page 9: Les petits mots
    {
      id: 'messages',
      pageNumber: 9,
      templateId: 'messages-v1',
      title: 'Les petits mots',
      subtitle: 'Les mots doux de ceux que j’aime',
      categoryTag: 'Messages',
      headerIcon: 'MessageCircle',
      backgroundTheme: 'warm-cream',
      status: 'draft',
      data: {
        parentsMessage: 'Nous sommes si fiers de toi mon trésor ! Continue de briller.',
        teacherMessage: 'Une élève curieuse, joyeuse et pleine d’imagination. Bravo Aminata !',
        friendsMessage: 'Tu es la meilleure copine du monde !',
        photoUrl: '/cahier-souvenirs/child.png',
        zoom: 1,
        rotation: 0,
      },
      elements: [],
    },

    // Page 10: Mes petits secrets
    {
      id: 'secrets',
      pageNumber: 10,
      templateId: 'secrets-v1',
      title: 'Mes petits secrets',
      subtitle: 'Chut... rien que pour moi !',
      categoryTag: 'Secrets',
      headerIcon: 'Lock',
      backgroundTheme: 'warm-cream',
      status: 'draft',
      data: {
        secretPower: 'Je peux parler aux oiseaux dans le jardin',
        hiddenTreasure: 'Une jolie pierre brillante cachée dans ma chambre',
        bigWish: 'Faire un grand voyage autour du monde avec ma famille',
        photoUrl: '/cahier-souvenirs/child.png',
        zoom: 1,
        rotation: 0,
      },
      elements: [],
    },
  ],
};

// Rétrocompatibilité : SCHOOL_MEMORY_BOOK_TEMPLATE_V1 pointe vers le nouveau modèle officiel 10 pages
export const SCHOOL_MEMORY_BOOK_TEMPLATE_V1 = OFFICIAL_MEMORY_BOOK_TEMPLATE_10_PAGES;

export const AVAILABLE_MEMORY_BOOK_TEMPLATES = [
  OFFICIAL_MEMORY_BOOK_TEMPLATE_10_PAGES,
];
