/**
 * Flood Fill Module — Petit Baobab
 *
 * Tolerance-based flood fill optimised for anti-aliased PNG coloring pages
 * generated by Flux (or similar). Two distinct thresholds:
 *
 *  • outlineThreshold (~40)  — luminance cutoff: any pixel whose perceived
 *    RGB channels are all below this value (and it is opaque enough) is treated as
 *    an outline edge the fill must NOT cross.
 *
 *  • fillTolerance   (~120)  — Euclidean RGBA distance: a neighbour pixel is
 *    added to the fill region when its colour distance to the *target* pixel
 *    (the one originally clicked) is within this value. A high tolerance lets
 *    the fill bleed through the soft anti-aliased fringe that surrounds every
 *    outline in a rasterised PNG.
 *
 *  Performance: uses a flat Int32Array ring-buffer for the BFS queue so every
 *  enqueue / dequeue is O(1) — avoids the O(n) cost of Array.shift().
 */

/* ------------------------------------------------------------------ */
/* Public types                                                        */
/* ------------------------------------------------------------------ */

export interface RGBA {
  r: number
  g: number
  b: number
  a: number
}

export interface FloodFillResult {
  maskCanvas: HTMLCanvasElement
  filledPixels: number
  targetColor: RGBA
}

export interface FloodFillOptions {
  /** X coordinate of the click (canvas-space, integer) */
  startX: number
  /** Y coordinate of the click (canvas-space, integer) */
  startY: number
  /** The colour to paint with */
  fillColor: RGBA
  /**
   * Euclidean RGBA distance below which a neighbouring pixel is considered
   * "same region" as the target pixel and therefore fillable.
   * Higher  → fill spreads more aggressively through anti-aliased edges.
   * Default = 120
   */
  fillTolerance?: number
  /**
   * Per-channel cutoff (0-255) for near-black outline detection.
   * Pixels whose RGB channels are all below this value are treated as boundaries.
   * Lower  → only the very darkest pixels count as outlines.
   * Default = 40
   */
  outlineThreshold?: number
  /**
   * Minimum alpha a pixel must have to be considered an outline.
   * Semi-transparent anti-alias fringes below this value are fillable.
   * Default = 80
   */
  outlineMinAlpha?: number
}

/* ------------------------------------------------------------------ */
/* Utility: hex colour string → RGBA                                   */
/* ------------------------------------------------------------------ */

export function hexToRgba(hex: string): RGBA {
  const m = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})?$/i.exec(hex)
  if (m) {
    return {
      r: parseInt(m[1], 16),
      g: parseInt(m[2], 16),
      b: parseInt(m[3], 16),
      a: m[4] !== undefined ? parseInt(m[4], 16) : 255,
    }
  }
  // Short hex (#RGB)
  const s = /^#?([a-f\d])([a-f\d])([a-f\d])$/i.exec(hex)
  if (s) {
    return {
      r: parseInt(s[1] + s[1], 16),
      g: parseInt(s[2] + s[2], 16),
      b: parseInt(s[3] + s[3], 16),
      a: 255,
    }
  }
  return { r: 0, g: 0, b: 0, a: 255 }
}

/* ------------------------------------------------------------------ */
/* Internal helpers                                                    */
/* ------------------------------------------------------------------ */

/**
 * Is this pixel dark + opaque enough to be part of an outline?
 */
function isOutlinePixel(
  r: number,
  g: number,
  b: number,
  a: number,
  threshold: number,
  minAlpha: number,
): boolean {
  return a > minAlpha && r <= threshold && g <= threshold && b <= threshold
}

/**
 * Euclidean colour distance (includes alpha, weighted at 50 %).
 * The alpha weight is reduced because anti-aliased fringes have varying
 * transparency that should not block the fill too aggressively.
 */
function colorDist(
  r1: number, g1: number, b1: number, a1: number,
  r2: number, g2: number, b2: number, a2: number,
): number {
  const dr = r1 - r2
  const dg = g1 - g2
  const db = b1 - b2
  const da = (a1 - a2) * 0.5 // alpha weighted down
  return Math.sqrt(dr * dr + dg * dg + db * db + da * da)
}

/* ------------------------------------------------------------------ */
/* Main flood-fill function                                            */
/* ------------------------------------------------------------------ */

/**
 * Performs a tolerance-based BFS flood fill on the supplied 2-D context.
 *
 * Returns a **mask canvas** (same dimensions) where only filled pixels are
 * non-transparent — this canvas can be layered on top of the original as a
 * Fabric.js Image object.  Returns `null` when no fill is possible (e.g.
 * the user clicked on an outline or on an area already filled with the
 * same colour).
 */
export function floodFill(
  ctx: CanvasRenderingContext2D,
  options: FloodFillOptions,
): FloodFillResult | null {
  const {
    startX,
    startY,
    fillColor,
    fillTolerance = 120,
    outlineThreshold = 40,
    outlineMinAlpha = 80,
  } = options

  const width = ctx.canvas.width
  const height = ctx.canvas.height

  // Bounds check
  if (startX < 0 || startX >= width || startY < 0 || startY >= height) {
    return null
  }

  const imgData = ctx.getImageData(0, 0, width, height)
  const data = imgData.data

  // ---- Sample the target (clicked) pixel ----
  const tIdx = (startY * width + startX) * 4
  const tR = data[tIdx]
  const tG = data[tIdx + 1]
  const tB = data[tIdx + 2]
  const tA = data[tIdx + 3]

  // Refuse to fill if clicked on an outline
  if (isOutlinePixel(tR, tG, tB, tA, outlineThreshold, outlineMinAlpha)) {
    return null
  }

  // Refuse to fill if already the chosen colour (distance < 15)
  if (colorDist(tR, tG, tB, tA, fillColor.r, fillColor.g, fillColor.b, fillColor.a) < 15) {
    return null
  }

  // ---- Prepare mask canvas for the result ----
  const maskCanvas = document.createElement("canvas")
  maskCanvas.width = width
  maskCanvas.height = height
  const maskCtx = maskCanvas.getContext("2d")
  if (!maskCtx) return null

  const maskImgData = maskCtx.createImageData(width, height)
  const maskData = maskImgData.data

  // ---- BFS with flat ring-buffer queue ----
  // Each pixel consumes 2 slots (x, y). Max pixels = width * height.
  const totalPixels = width * height
  const buf = new Int32Array(totalPixels * 2)
  let head = 0
  let tail = 0

  const visited = new Uint8Array(totalPixels)

  // Enqueue start pixel
  buf[tail++] = startX
  buf[tail++] = startY
  visited[startY * width + startX] = 1

  // Neighbour offsets (right, left, down, up)
  const dx = [1, -1, 0, 0]
  const dy = [0, 0, 1, -1]

  let filledPixels = 0

  while (head < tail) {
    const cx = buf[head++]
    const cy = buf[head++]

    // Paint this pixel into the mask
    const mIdx = (cy * width + cx) * 4
    maskData[mIdx] = fillColor.r
    maskData[mIdx + 1] = fillColor.g
    maskData[mIdx + 2] = fillColor.b
    maskData[mIdx + 3] = fillColor.a
    filledPixels++

    // Explore neighbours
    for (let d = 0; d < 4; d++) {
      const nx = cx + dx[d]
      const ny = cy + dy[d]

      if (nx < 0 || nx >= width || ny < 0 || ny >= height) continue

      const nLinear = ny * width + nx
      if (visited[nLinear]) continue

      // Read neighbour colour
      const nIdx = nLinear * 4
      const nr = data[nIdx]
      const ng = data[nIdx + 1]
      const nb = data[nIdx + 2]
      const na = data[nIdx + 3]

      // Mark visited regardless of outcome (avoid re-checking)
      visited[nLinear] = 1

      // Stop at outlines
      if (isOutlinePixel(nr, ng, nb, na, outlineThreshold, outlineMinAlpha)) {
        continue
      }

      // Fill if colour distance to target is within tolerance
      const dist = colorDist(nr, ng, nb, na, tR, tG, tB, tA)
      if (dist <= fillTolerance) {
        buf[tail++] = nx
        buf[tail++] = ny
      }
    }
  }

  // If nothing was filled (only the single start pixel), still return the mask
  maskCtx.putImageData(maskImgData, 0, 0)

  return {
    maskCanvas,
    filledPixels,
    targetColor: { r: tR, g: tG, b: tB, a: tA },
  }
}


