import { Story, StoryTheme } from "./types"

export const STORY_THEMES: StoryTheme[] = [
  {
    id: "amitie",
    label: "Amitié",
    icon: "Heart",
    color: "#7D6AF8",
    bgLight: "#F0EDFF",
    textColor: "#FFFFFF",
  },
  {
    id: "nature",
    label: "Nature",
    icon: "Leaf",
    color: "#00C9A7",
    bgLight: "#E6FBF7",
    textColor: "#FFFFFF",
  },
  {
    id: "education",
    label: "Éducation",
    icon: "BookOpen",
    color: "#FF9671",
    bgLight: "#FFF2EE",
    textColor: "#FFFFFF",
  },
  {
    id: "aventure",
    label: "Aventure",
    icon: "Star",
    color: "#FF6F91",
    bgLight: "#FFEEF2",
    textColor: "#FFFFFF",
  },
  {
    id: "culture",
    label: "Culture",
    icon: "Music",
    color: "#0081CF",
    bgLight: "#E8F5FE",
    textColor: "#FFFFFF",
  },
  {
    id: "famille",
    label: "Famille",
    icon: "Users",
    color: "#FFC75F",
    bgLight: "#FFF8EA",
    textColor: "#3B2416",
  },
]

export const MY_STORIES: Story[] = [
  {
    id: "moussa-secret-baobab",
    title: "Moussa et le secret du baobab",
    description: "Une belle aventure sur l'amitié et la découverte de la nature.",
    coverUrl: "/illustrations/histoires/story-moussa-baobab.webp",
    ageRange: "6-8 ans",
    themeId: "aventure",
    themeLabel: "Aventure",
    category: "Aventure",
    categoryColor: "#10B981",
    country: "Sénégal",
    environment: "Savane",
    pages: [
      {
        pageNumber: 1,
        text: "Au cœur du village de Koura, un immense baobab séculaire veillait sur les enfants. Moussa adorait s'asseoir à son ombre pour écouter le vent chanter à travers ses branches dorées.",
        illustrationUrl: "/illustrations/histoires/story-moussa-baobab.webp",
      },
      {
        pageNumber: 2,
        text: "Un matin étincelant, un petit éléphant curieux s'approcha doucement de Moussa. Ses grands yeux brillaient d'une malice joyeuse. Ensemble, ils décidèrent d'explorer les secrets cachés du vieux tronc.",
        illustrationUrl: "/illustrations/histoires/story-moussa-baobab.webp",
      },
      {
        pageNumber: 3,
        text: "Au creux de l'écorce, ils découvrirent une graine magique qui luisait doucement sous les rayons du soleil couchant. « Prends-en soin », semblait murmurer l'arbre protecteur.",
        illustrationUrl: "/illustrations/histoires/story-moussa-baobab.webp",
      },
    ],
  },
  {
    id: "aicha-marche-couleurs",
    title: "Aïcha et le marché des couleurs",
    description: "Aïcha découvre la richesse de sa culture et apprend le partage.",
    coverUrl: "/illustrations/histoires/story-aicha-marche.webp",
    ageRange: "6-8 ans",
    themeId: "culture",
    themeLabel: "Culture",
    category: "Culture",
    categoryColor: "#F59E0B",
    country: "Côte d'Ivoire",
    environment: "Marché traditionnel",
    pages: [
      {
        pageNumber: 1,
        text: "Le marché grouillait de rires, d'épices parfumées et de pagnes éclatants. Aïcha marchait aux côtés de sa grand-mère, émerveillée par tant de beautés entremêlées.",
        illustrationUrl: "/illustrations/histoires/story-aicha-marche.webp",
      },
      {
        pageNumber: 2,
        text: "Elle fit la rencontre d'une jeune marchande qui lui montra comment chaque teinte de tissu racontait l'histoire et les proverbes d'un peuple fier et généreux.",
        illustrationUrl: "/illustrations/histoires/story-aicha-marche.webp",
      },
      {
        pageNumber: 3,
        text: "En partageant ses mangues mûres avec d'autres enfants, Aïcha comprit que la plus belle des couleurs est celle de la bienveillance partagée.",
        illustrationUrl: "/illustrations/histoires/story-aicha-marche.webp",
      },
    ],
  },
  {
    id: "petite-tortue-fleuve",
    title: "La petite tortue et le fleuve",
    description: "Une histoire sur la protection de l'environnement et de l'eau.",
    coverUrl: "/illustrations/histoires/story-tortue-fleuve.webp",
    ageRange: "5-7 ans",
    themeId: "nature",
    themeLabel: "Nature",
    category: "Nature",
    categoryColor: "#059669",
    country: "Mali",
    environment: "Bords du fleuve Niger",
    pages: [
      {
        pageNumber: 1,
        text: "Près des berges calmes du grand fleuve, une petite tortue aux motifs dorés contemplait les reflets scintillants de l'eau claire.",
        illustrationUrl: "/illustrations/histoires/story-tortue-fleuve.webp",
      },
      {
        pageNumber: 2,
        text: "Deux enfants du village vinrent s'asseoir près d'elle et promirent de protéger les berges et la végétation qui lui offraient refuge.",
        illustrationUrl: "/illustrations/histoires/story-tortue-fleuve.webp",
      },
      {
        pageNumber: 3,
        text: "L'eau resta pure et vivante pour toutes les créatures du fleuve, grâce à l'attention et au respect de chacun.",
        illustrationUrl: "/illustrations/histoires/story-tortue-fleuve.webp",
      },
    ],
  },
  {
    id: "reve-de-salif",
    title: "Le rêve de Salif",
    description: "Un jeune garçon qui croit en lui et réalise ses rêves d'écolier.",
    coverUrl: "/illustrations/histoires/story-salif-reve.webp",
    ageRange: "7-10 ans",
    themeId: "education",
    themeLabel: "Éducation",
    category: "Éducation",
    categoryColor: "#8B5CF6",
    country: "Burkina Faso",
    environment: "École de village",
    pages: [
      {
        pageNumber: 1,
        text: "Son cartable en bandoulière et le sourire éclatant, Salif marchait vers son école avec la ferme résolution de percer le mystère des constellations.",
        illustrationUrl: "/illustrations/histoires/story-salif-reve.webp",
      },
      {
        pageNumber: 2,
        text: "Dans sa classe baignée de soleil, il dessinait des maquettes de fusées inspirées des contes de voyageurs que lui racontait son grand-père.",
        illustrationUrl: "/illustrations/histoires/story-salif-reve.webp",
      },
      {
        pageNumber: 3,
        text: "Chaque mot appris devenait une passerelle vers l'avenir : Salif savait désormais que tout rêve commence par la curiosité et l'effort quotidien.",
        illustrationUrl: "/illustrations/histoires/story-salif-reve.webp",
      },
    ],
  },
]

export const RECOMMENDED_STORIES: Story[] = [
  {
    id: "lion-et-petit-garcon",
    title: "Le lion et le petit garçon",
    description: "Le courage n'est pas de faire peur, mais de savoir tendre la main.",
    coverUrl: "/illustrations/histoires/story-lion-garcon.webp",
    ageRange: "5-7 ans",
    themeId: "aventure",
    themeLabel: "Aventure",
    category: "Aventure",
    categoryColor: "#10B981",
    country: "Kenya",
    environment: "Savane ouverte",
    isChildFavorite: true,
    pages: [
      {
        pageNumber: 1,
        text: "Sous la chaleur bienveillante de l'après-midi, un jeune berger fit face à un majestueux lion allongé près d'un grand rocher ocre.",
        illustrationUrl: "/illustrations/histoires/story-lion-garcon.webp",
      },
      {
        pageNumber: 2,
        text: "Sans crainte mais avec un profond respect, le garçon partagea une calebasse d'eau fraîche avec le roi des animaux, qui le salua d'un hochement calme.",
        illustrationUrl: "/illustrations/histoires/story-lion-garcon.webp",
      },
    ],
  },
  {
    id: "petite-agricultrice",
    title: "La petite agricultrice",
    description: "Semer l'espoir et cultiver la terre avec amour et patience.",
    coverUrl: "/illustrations/histoires/story-agricultrice.webp",
    ageRange: "6-8 ans",
    themeId: "nature",
    themeLabel: "Nature",
    category: "Nature",
    categoryColor: "#059669",
    country: "Bénin",
    environment: "Champs fertiles",
    isChildFavorite: true,
    pages: [
      {
        pageNumber: 1,
        text: "Aminata s'agenouillait avec délicatesse dans la terre meuble pour mettre en terre de jeunes pousses de maïs et de baobab nain.",
        illustrationUrl: "/illustrations/histoires/story-agricultrice.webp",
      },
      {
        pageNumber: 2,
        text: "Chaque matin, la rosée nourrissait son jardin verdoyant, qui devint la fierté de toute sa famille et de son école.",
        illustrationUrl: "/illustrations/histoires/story-agricultrice.webp",
      },
    ],
  },
  {
    id: "voyage-de-koffi",
    title: "Le voyage de Koffi",
    description: "Une odyssée étoilée à la poursuite d'une comète bienveillante.",
    coverUrl: "/illustrations/histoires/story-koffi.webp",
    ageRange: "7-10 ans",
    themeId: "aventure",
    themeLabel: "Rêve",
    category: "Rêve",
    categoryColor: "#3B82F6",
    country: "Togo",
    environment: "Nuit étoilée sahélienne",
    isChildFavorite: true,
    pages: [
      {
        pageNumber: 1,
        text: "La nuit tombée, les collines s'habillaient d'un bleu profond parsemé de mille étoiles. Koffi contemplait le ciel avec émerveillement.",
        illustrationUrl: "/illustrations/histoires/story-koffi.webp",
      },
      {
        pageNumber: 2,
        text: "En rêve, il s'éleva au-dessus des cimes des arbres, guidé par une constellation chantante qui lui murmurait la beauté du monde.",
        illustrationUrl: "/illustrations/histoires/story-koffi.webp",
      },
    ],
  },
  {
    id: "ensemble-cest-mieux",
    title: "Ensemble, c'est mieux",
    description: "Quand les enfants unissent leurs cœurs et leurs forces.",
    coverUrl: "/illustrations/histoires/story-ensemble.webp",
    ageRange: "5-7 ans",
    themeId: "amitie",
    themeLabel: "Amitié",
    category: "Amitié",
    categoryColor: "#EC4899",
    country: "Guinée",
    environment: "Cour de village",
    isChildFavorite: true,
    pages: [
      {
        pageNumber: 1,
        text: "Cinq amis décidèrent de réparer ensemble la balançoire de la place centrale pour que tous les petits du quartier puissent jouer en riant.",
        illustrationUrl: "/illustrations/histoires/story-ensemble.webp",
      },
      {
        pageNumber: 2,
        text: "Chacun apporta une corde, une planche et surtout sa bonne humeur. Ensemble, le travail devint une véritable fête !",
        illustrationUrl: "/illustrations/histoires/story-ensemble.webp",
      },
    ],
  },
]
