"use client"

import { useEffect, useState } from "react"
import { useAuthStore } from "@/lib/auth-store"
import { useRouter } from "next/navigation"
import { useI18n } from "@/lib/i18n-provider"
import { motion, AnimatePresence } from "framer-motion"
import {
  Sparkles,
  Palette,
  BookOpen,
  HelpCircle,
  GraduationCap,
  Star,
  ArrowRight,
  ChevronDown,
  Layers,
  CheckCircle2,
  Lock,
} from "lucide-react"
import Image from "next/image"

export default function LandingPage() {
  const router = useRouter()
  const { t, lang, setLanguage } = useI18n()
  const { user, account, checkSession, logout } = useAuthStore()
  
  const [faqOpen, setFaqOpen] = useState<Record<number, boolean>>({})

  useEffect(() => {
    checkSession()
  }, [checkSession])

  const toggleFaq = (index: number) => {
    setFaqOpen((prev) => ({ ...prev, [index]: !prev[index] }))
  }

  const handleLangToggle = () => {
    setLanguage(lang === "fr" ? "en" : "fr")
  }

  // FAQ Items
  const faqItems = [
    {
      q: lang === "fr" ? "Qu'est-ce que Petit Baobab ?" : "What is Petit Baobab?",
      a: lang === "fr" 
        ? "Petit Baobab est une application éducative et créative pour les enfants de 3 à 7 ans au Burkina Faso. Elle allie coloriage traditionnel, création de contes et dessins magiques générés par IA avec des thèmes locaux et adaptés." 
        : "Petit Baobab is an educational and creative application for children aged 3 to 7 in Burkina Faso. It combines traditional coloring, storybooks creation, and AI-generated magic drawings with adapted local themes."
    },
    {
      q: lang === "fr" ? "Comment fonctionne le système d'étoiles ?" : "How does the stars system work?",
      a: lang === "fr" 
        ? "Chaque création de dessin magique par IA consomme des étoiles (de 1 à 3 selon le style choisi). Vous recevez 5 étoiles gratuites à l'inscription, et vous pouvez recharger via Orange Money/Moov Money ou en vous abonnant." 
        : "Each AI magic drawing generation consumes stars (from 1 to 3 depending on the selected style). You receive 5 free stars upon sign up, and you can top up via Orange Money/Moov Money or by subscribing."
    },
    {
      q: lang === "fr" ? "L'application est-elle adaptée aux écoles ?" : "Is the application suitable for schools?",
      a: lang === "fr" 
        ? "Oui ! Nous préparons un espace dédié aux écoles (/school) avec un tableau de bord pour les enseignants, la gestion des classes et des impressions en volume pour tous les élèves." 
        : "Yes! We are preparing a dedicated school space (/school) with a teacher dashboard, classroom management, and bulk printing options for all students."
    },
    {
      q: lang === "fr" ? "Vos images sont-elles adaptées et sécurisées ?" : "Are your images safe and appropriate?",
      a: lang === "fr" 
        ? "Absolument. Nous appliquons des filtres de sécurité stricts (Safety Filters) côté serveur pour garantir que tout le contenu généré par l'IA ou proposé dans notre catalogue est 100% adapté aux enfants en bas âge." 
        : "Absolutely. We enforce strict safety filters on the server side to ensure that all content generated by AI or offered in our catalog is 100% child-friendly."
    }
  ]

  return (
    <div className="min-h-screen bg-[#FFF9F2] text-[#3B2416] font-sans antialiased overflow-x-hidden pb-12 select-none">
      
      {/* --- HEADER --- */}
      <header className="sticky top-0 bg-[#FFF9F2]/90 backdrop-blur-md border-b-4 border-[#3B2416] z-50 px-4 lg:px-8 py-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          {/* Logo */}
          <Link href="/" className="flex items-center gap-2 cursor-pointer">
            <Image
              src="/illustrations/logo-petit-baobab.webp"
              alt="Petit Baobab"
              width={160}
              height={50}
              className="w-auto h-[45px] object-contain"
              priority
            />
          </Link>

          {/* Navigation links */}
          <nav className="hidden md:flex items-center gap-6 font-bold text-sm text-[#7A6A5E]">
            <a href="#features" className="hover:text-[#3B2416] transition-colors">{lang === "fr" ? "Fonctionnalités" : "Features"}</a>
            <a href="#how-it-works" className="hover:text-[#3B2416] transition-colors">{lang === "fr" ? "Comment ça marche" : "How it works"}</a>
            <a href="#pricing" className="hover:text-[#3B2416] transition-colors">{lang === "fr" ? "Tarifs" : "Pricing"}</a>
            <a href="#faq" className="hover:text-[#3B2416] transition-colors">FAQ</a>
            <button onClick={() => router.push("/school")} className="flex items-center gap-1 text-[#6D4AFF] hover:text-[#6D4AFF]/80 transition-colors font-extrabold cursor-pointer">
              <GraduationCap className="w-4 h-4" />
              <span>{lang === "fr" ? "Écoles" : "Schools"}</span>
            </button>
          </nav>

          {/* Action buttons */}
          <div className="flex items-center gap-3">
            <button
              onClick={handleLangToggle}
              className="px-2.5 py-1 text-xs font-bold border-2 border-[#3B2416] bg-white rounded-full shadow-[2px_2px_0px_0px_#3B2416] hover:bg-neutral-50 cursor-pointer"
            >
              {lang === "fr" ? "EN" : "FR"}
            </button>

            {user ? (
              <>
                <button
                  onClick={() => router.push("/dashboard")}
                  className="px-4 py-2 bg-[#DDF26B] hover:bg-[#BCE83E] border-2 border-[#3B2416] text-[#3B2416] font-bold text-xs rounded-full shadow-[3px_3px_0px_0px_#3B2416] active:translate-y-0.5 active:shadow-[1px_1px_0px_0px_#3B2416] transition-all cursor-pointer"
                >
                  {lang === "fr" ? "Mon Espace" : "My Dashboard"}
                </button>
                <button
                  onClick={async () => {
                    await logout()
                    router.refresh()
                  }}
                  className="px-3.5 py-2 bg-white hover:bg-red-50 text-red-500 border-2 border-[#3B2416] font-bold text-xs rounded-full shadow-[3px_3px_0px_0px_#3B2416] active:translate-y-0.5 active:shadow-[1px_1px_0px_0px_#3B2416] transition-all cursor-pointer"
                >
                  {lang === "fr" ? "Quitter" : "Sign Out"}
                </button>
              </>
            ) : (
              <>
                <button
                  onClick={() => router.push("/login")}
                  className="hidden sm:inline-block px-4 py-2 bg-white hover:bg-neutral-50 border-2 border-[#3B2416] text-[#3B2416] font-bold text-xs rounded-full shadow-[3px_3px_0px_0px_#3B2416] active:translate-y-0.5 active:shadow-[1px_1px_0px_0px_#3B2416] transition-all cursor-pointer"
                >
                  {lang === "fr" ? "Se connecter" : "Log In"}
                </button>
                <button
                  onClick={() => router.push("/login?tab=signup")}
                  className="px-4 py-2 bg-[#FFE08A] hover:bg-[#FFE08A]/90 border-2 border-[#3B2416] text-[#3B2416] font-bold text-xs rounded-full shadow-[3px_3px_0px_0px_#3B2416] active:translate-y-0.5 active:shadow-[1px_1px_0px_0px_#3B2416] transition-all cursor-pointer"
                >
                  {lang === "fr" ? "Créer un compte" : "Register"}
                </button>
              </>
            )}
          </div>
        </div>
      </header>

      {/* --- HERO SECTION --- */}
      <section className="max-w-7xl mx-auto px-4 lg:px-8 py-12 md:py-20 flex flex-col-reverse lg:grid lg:grid-cols-2 gap-12 items-center">
        
        {/* Left Info Column */}
        <motion.div
          initial={{ opacity: 0, x: -30 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5 }}
          className="flex flex-col gap-6"
        >
          {/* Tag */}
          <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-[#DDF26B]/40 border-2 border-[#3B2416] rounded-full w-max text-xs font-bold shadow-[2px_2px_0px_0px_#3B2416]">
            <Sparkles className="w-3.5 h-3.5 text-[#6D4AFF]" />
            <span>{lang === "fr" ? "5 ÉTOILES OFFERTES À L'INSCRIPTION" : "5 FREE STARS UPON SIGNUP"}</span>
          </div>

          {/* Main Title */}
          <h1 className="text-[38px] md:text-[54px] font-extrabold text-[#3B2416] leading-tight max-w-xl">
            {lang === "fr" 
              ? "Éveillez la créativité de vos enfants !" 
              : "Awaken your children's creativity!"}
          </h1>

          {/* Subtitle */}
          <p className="text-base md:text-lg font-medium text-[#7A6A5E] leading-relaxed max-w-lg">
            {lang === "fr"
              ? "Petit Baobab est le premier studio de coloriage interactif et éducatif conçu pour les enfants de 3 à 7 ans au Burkina Faso. Coloriages locaux, livres personnalisés et dessins magiques générés par IA !"
              : "Petit Baobab is the first interactive and educational coloring studio designed for children aged 3 to 7 in Burkina Faso. Local coloring themes, custom book creation, and AI-generated magic outlines!"}
          </p>

          {/* Action Buttons */}
          <div className="flex flex-wrap items-center gap-4 mt-2">
            {user ? (
              <button
                onClick={() => router.push("/dashboard")}
                className="h-[58px] px-8 bg-[#6D4AFF] text-white border-2 border-[#3B2416] rounded-2xl font-bold text-base shadow-[4px_4px_0px_0px_#3B2416] hover:bg-[#6D4AFF]/95 active:translate-y-0.5 active:shadow-[2px_2px_0px_0px_#3B2416] transition-all flex items-center gap-2 cursor-pointer"
              >
                <span>{lang === "fr" ? "Accéder à mon espace" : "Access My Dashboard"}</span>
                <ArrowRight className="w-5 h-5" />
              </button>
            ) : (
              <>
                <button
                  onClick={() => router.push("/login?tab=signup")}
                  className="h-[58px] px-8 bg-[#6D4AFF] text-white border-2 border-[#3B2416] rounded-2xl font-bold text-base shadow-[4px_4px_0px_0px_#3B2416] hover:bg-[#6D4AFF]/95 active:translate-y-0.5 active:shadow-[2px_2px_0px_0px_#3B2416] transition-all flex items-center gap-2 cursor-pointer"
                >
                  <span>{lang === "fr" ? "Commencer gratuitement" : "Start Free Now"}</span>
                  <ArrowRight className="w-5 h-5" />
                </button>
                <button
                  onClick={() => router.push("/login")}
                  className="h-[58px] px-8 bg-white border-2 border-[#3B2416] text-[#3B2416] font-bold text-base rounded-2xl shadow-[4px_4px_0px_0px_#3B2416] hover:bg-neutral-50 active:translate-y-0.5 active:shadow-[2px_2px_0px_0px_#3B2416] transition-all cursor-pointer"
                >
                  {lang === "fr" ? "Découvrir Petit Baobab" : "Discover More"}
                </button>
              </>
            )}
          </div>
        </motion.div>

        {/* Right Mascot Column */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="relative flex justify-center"
        >
          {/* Main Baobab Frame */}
          <div className="w-[320px] md:w-[420px] h-[320px] md:h-[420px] rounded-[48px] border-4 border-[#3B2416] bg-gradient-to-tr from-[#FFE08A] to-[#DDF26B] shadow-[8px_8px_0px_0px_#3B2416] flex items-center justify-center p-6 relative overflow-hidden">
            <Image
              src="/illustrations/mascot_awa.webp"
              alt="Mascot Awa"
              width={260}
              height={260}
              className="w-auto h-[260px] object-contain object-bottom drop-shadow-xl mt-6 animate-pulse"
              onError={(e) => {
                e.currentTarget.src = "https://api.dicebear.com/9.x/fun-emoji/svg?seed=Awa"
              }}
            />
            {/* Badges details */}
            <div className="absolute top-4 right-4 bg-white border-2 border-[#3B2416] p-2 rounded-2xl flex items-center gap-1 shadow-sm">
              <Star className="w-4 h-4 text-amber-500 fill-current" />
              <span className="text-xs font-bold">5 {lang === "fr" ? "étoiles offertes" : "free stars"}</span>
            </div>
          </div>
        </motion.div>
      </section>

      {/* --- FEATURES SECTION --- */}
      <section id="features" className="max-w-7xl mx-auto px-4 lg:px-8 py-16 border-t-4 border-dashed border-[#3B2416]">
        <div className="text-center mb-12">
          <h2 className="text-[32px] md:text-[40px] font-extrabold text-[#3B2416] leading-tight">
            {lang === "fr" ? "Que propose Petit Baobab ?" : "What does Petit Baobab offer?"}
          </h2>
          <p className="text-base font-bold text-[#7A6A5E] mt-2 max-w-xl mx-auto">
            {lang === "fr"
              ? "Des outils créatifs pensés pour stimuler l'apprentissage et l'expression artistique de vos enfants."
              : "Creative tools designed to stimulate learning and artistic expression for your children."}
          </p>
        </div>

        {/* Feature Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          
          {/* Card 1 */}
          <div className="bg-white border-4 border-[#3B2416] rounded-[28px] p-6 shadow-[5px_5px_0px_0px_#3B2416] flex flex-col gap-4">
            <div className="w-12 h-12 rounded-[16px] bg-[#FFE08A] border-2 border-[#3B2416] flex items-center justify-center text-[#3B2416]">
              <Sparkles className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-extrabold">{lang === "fr" ? "Dessin Magique IA" : "AI Magic Drawing"}</h3>
            <p className="text-sm text-[#7A6A5E] font-medium leading-relaxed">
              {lang === "fr"
                ? "L'enfant décrit l'idée de son choix, et notre intelligence artificielle génère instantanément un coloriage unique et sûr."
                : "The child describes the idea of their choice, and our artificial intelligence instantly generates a unique and safe outline coloring page."}
            </p>
          </div>

          {/* Card 2 */}
          <div className="bg-white border-4 border-[#3B2416] rounded-[28px] p-6 shadow-[5px_5px_0px_0px_#3B2416] flex flex-col gap-4">
            <div className="w-12 h-12 rounded-[16px] bg-[#DDF26B] border-2 border-[#3B2416] flex items-center justify-center text-[#3B2416]">
              <Palette className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-extrabold">{lang === "fr" ? "Bibliothèque Locale" : "Local Catalog"}</h3>
            <p className="text-sm text-[#7A6A5E] font-medium leading-relaxed">
              {lang === "fr"
                ? "Des dizaines d'illustrations prêtes à colorier, illustrant des animaux, des fruits et la culture du Burkina Faso (instruments, villages, tenues)."
                : "Dozens of illustrations ready to color, featuring animals, fruits, and the local culture of Burkina Faso (instruments, villages, traditions)."}
            </p>
          </div>

          {/* Card 3 */}
          <div className="bg-white border-4 border-[#3B2416] rounded-[28px] p-6 shadow-[5px_5px_0px_0px_#3B2416] flex flex-col gap-4">
            <div className="w-12 h-12 rounded-[16px] bg-[#FFC4A8] border-2 border-[#3B2416] flex items-center justify-center text-[#3B2416]">
              <BookOpen className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-extrabold">{lang === "fr" ? "Création de Livres" : "Book Customization"}</h3>
            <p className="text-sm text-[#7A6A5E] font-medium leading-relaxed">
              {lang === "fr"
                ? "Assemblez les dessins préférés de votre enfant pour créer un véritable livre de coloriage relié, exportable au format PDF A4 en un clic."
                : "Assemble your child's favorite drawings to create a real customized coloring book, exportable as A4 PDF in one click."}
            </p>
          </div>

        </div>
      </section>

      {/* --- HOW IT WORKS --- */}
      <section id="how-it-works" className="max-w-7xl mx-auto px-4 lg:px-8 py-16 bg-[#F8FAFC] border-4 border-[#3B2416] rounded-[36px] shadow-[6px_6px_0px_0px_#3B2416]">
        <div className="text-center mb-12">
          <h2 className="text-[32px] md:text-[40px] font-extrabold text-[#3B2416] leading-tight">
            {lang === "fr" ? "Comment ça fonctionne ?" : "How does it work?"}
          </h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-start relative">
          {/* Step 1 */}
          <div className="flex flex-col items-center text-center gap-3">
            <div className="w-10 h-10 rounded-full bg-[#FFE08A] border-2 border-[#3B2416] flex items-center justify-center font-bold text-sm">1</div>
            <h4 className="font-extrabold text-lg">{lang === "fr" ? "Création de compte" : "Create Account"}</h4>
            <p className="text-xs text-[#7A6A5E] font-bold leading-relaxed max-w-[240px]">
              {lang === "fr" 
                ? "Inscrivez-vous gratuitement en 1 clic. Recevez immédiatement 5 étoiles offertes." 
                : "Sign up for free in 1 click. Immediately get 5 free stars in your wallet."}
            </p>
          </div>

          {/* Step 2 */}
          <div className="flex flex-col items-center text-center gap-3">
            <div className="w-10 h-10 rounded-full bg-[#DDF26B] border-2 border-[#3B2416] flex items-center justify-center font-bold text-sm">2</div>
            <h4 className="font-extrabold text-lg">{lang === "fr" ? "Dessiner et Imaginer" : "Imagine & Draw"}</h4>
            <p className="text-xs text-[#7A6A5E] font-bold leading-relaxed max-w-[240px]">
              {lang === "fr" 
                ? "Laissez votre enfant choisir ses mascottes, générer ses dessins avec l'IA ou colorier en ligne." 
                : "Let your child choose their mascots, generate AI sketches, or color online directly."}
            </p>
          </div>

          {/* Step 3 */}
          <div className="flex flex-col items-center text-center gap-3">
            <div className="w-10 h-10 rounded-full bg-[#FFC4A8] border-2 border-[#3B2416] flex items-center justify-center font-bold text-sm">3</div>
            <h4 className="font-extrabold text-lg">{lang === "fr" ? "Imprimer et colorier" : "Print & Color"}</h4>
            <p className="text-xs text-[#7A6A5E] font-bold leading-relaxed max-w-[240px]">
              {lang === "fr" 
                ? "Téléchargez au format PDF A4 et imprimez le dessin pour continuer à colorier sur papier !" 
                : "Download in A4 PDF format and print the drawings to color physically on paper!"}
            </p>
          </div>
        </div>
      </section>

      {/* --- PRICING SECTION --- */}
      <section id="pricing" className="max-w-7xl mx-auto px-4 lg:px-8 py-16">
        <div className="text-center mb-12">
          <h2 className="text-[32px] md:text-[40px] font-extrabold text-[#3B2416] leading-tight">
            {lang === "fr" ? "Nos Forfaits Parents & Écoles" : "Our Plans for Parents & Schools"}
          </h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          
          {/* Plan Free */}
          <div className="bg-white border-4 border-[#3B2416] rounded-[28px] p-6 shadow-[4px_4px_0px_0px_#3B2416] flex flex-col justify-between">
            <div>
              <h3 className="text-lg font-extrabold text-[#64748B] uppercase">{lang === "fr" ? "Gratuit" : "Free"}</h3>
              <div className="text-[32px] font-extrabold mt-2 text-[#3B2416]">0 FCFA</div>
              <ul className="text-xs font-bold text-[#7A6A5E] flex flex-col gap-2 mt-6">
                <li className="flex items-center gap-1.5">✓ 5 étoiles offertes</li>
                <li className="flex items-center gap-1.5">✓ Bibliothèque gratuite</li>
                <li className="flex items-center gap-1.5">✓ Filigrane sur les PDF</li>
              </ul>
            </div>
            <button onClick={() => router.push("/login?tab=signup")} className="w-full h-11 border-2 border-[#3B2416] rounded-xl font-bold text-xs mt-8 bg-neutral-50 hover:bg-neutral-100 transition-colors cursor-pointer">
              {lang === "fr" ? "Commencer" : "Start Free"}
            </button>
          </div>

          {/* Plan Découverte */}
          <div className="bg-white border-4 border-[#3B2416] rounded-[28px] p-6 shadow-[4px_4px_0px_0px_#3B2416] flex flex-col justify-between relative">
            <div>
              <h3 className="text-lg font-extrabold text-[#D97706] uppercase">{lang === "fr" ? "Découverte" : "Discovery"}</h3>
              <div className="text-[32px] font-extrabold mt-2 text-[#3B2416]">1 500 FCFA <span className="text-xs font-medium text-[#64748B]">{lang === "fr" ? "/ mois" : "/ mo"}</span></div>
              <ul className="text-xs font-bold text-[#7A6A5E] flex flex-col gap-2 mt-6">
                <li className="flex items-center gap-1.5">✓ 100 étoiles incluses</li>
                <li className="flex items-center gap-1.5">✓ Aucune publicité</li>
                <li className="flex items-center gap-1.5">✓ Téléchargements PDF sans filigrane</li>
              </ul>
            </div>
            <button onClick={() => router.push("/login")} className="w-full h-11 border-2 border-[#3B2416] rounded-xl font-bold text-xs mt-8 bg-[#FFE08A] hover:bg-[#FFE08A]/90 transition-colors cursor-pointer">
              {lang === "fr" ? "S'abonner" : "Subscribe"}
            </button>
          </div>

          {/* Plan Super Baobab */}
          <div className="bg-white border-4 border-[#6D4AFF] rounded-[28px] p-6 shadow-[4px_4px_0px_0px_#6D4AFF] flex flex-col justify-between relative scale-105 border-t-[10px]">
            <div className="absolute -top-3.5 left-1/2 -translate-x-1/2 bg-[#6D4AFF] text-white px-3 py-0.5 rounded-full text-[10px] font-extrabold tracking-wider uppercase">
              {lang === "fr" ? "Recommandé" : "Best Value"}
            </div>
            <div>
              <h3 className="text-lg font-extrabold text-[#6D4AFF] uppercase">Super Baobab</h3>
              <div className="text-[32px] font-extrabold mt-2 text-[#3B2416]">3 500 FCFA <span className="text-xs font-medium text-[#64748B]">{lang === "fr" ? "/ mois" : "/ mo"}</span></div>
              <ul className="text-xs font-bold text-[#7A6A5E] flex flex-col gap-2 mt-6">
                <li className="flex items-center gap-1.5">✓ 300 étoiles incluses</li>
                <li className="flex items-center gap-1.5">✓ Multi-profils (3 enfants)</li>
                <li className="flex items-center gap-1.5">✓ Générations IA prioritaires</li>
              </ul>
            </div>
            <button onClick={() => router.push("/login")} className="w-full h-11 border-2 border-[#6D4AFF] rounded-xl font-bold text-xs mt-8 bg-[#6D4AFF] text-white hover:bg-[#6D4AFF]/95 transition-colors cursor-pointer shadow-md">
              {lang === "fr" ? "S'abonner" : "Subscribe"}
            </button>
          </div>

          {/* Plan École */}
          <div className="bg-white border-4 border-[#3B2416] rounded-[28px] p-6 shadow-[4px_4px_0px_0px_#3B2416] flex flex-col justify-between">
            <div>
              <h3 className="text-lg font-extrabold text-[#0284C7] uppercase">{lang === "fr" ? "École / Pro" : "Schools / Pro"}</h3>
              <div className="text-[32px] font-extrabold mt-2 text-[#3B2416]">20 000 FCFA <span className="text-xs font-medium text-[#64748B]">{lang === "fr" ? "/ mois" : "/ mo"}</span></div>
              <ul className="text-xs font-bold text-[#7A6A5E] flex flex-col gap-2 mt-6">
                <li className="flex items-center gap-1.5">✓ Étoiles illimitées</li>
                <li className="flex items-center gap-1.5">✓ Tableau de bord enseignant</li>
                <li className="flex items-center gap-1.5">✓ Gestion des classes et élèves</li>
              </ul>
            </div>
            <button onClick={() => router.push("/school")} className="w-full h-11 border-2 border-[#3B2416] rounded-xl font-bold text-xs mt-8 bg-[#E0F2FE] hover:bg-[#E0F2FE]/90 transition-colors cursor-pointer">
              {lang === "fr" ? "Découvrir l'Espace École" : "Discover Schools"}
            </button>
          </div>

        </div>
      </section>

      {/* --- FAQ SECTION --- */}
      <section id="faq" className="max-w-4xl mx-auto px-4 py-16">
        <h2 className="text-[32px] font-extrabold text-[#3B2416] text-center mb-8">FAQ</h2>

        <div className="flex flex-col gap-4">
          {faqItems.map((item, idx) => (
            <div key={idx} className="bg-white border-2 border-[#3B2416] rounded-2xl overflow-hidden shadow-sm">
              <button
                onClick={() => toggleFaq(idx)}
                className="w-full px-5 py-4 font-bold text-left flex items-center justify-between hover:bg-neutral-50 cursor-pointer"
              >
                <span>{item.q}</span>
                <ChevronDown className={`w-5 h-5 text-[#7A6A5E] transition-transform ${faqOpen[idx] ? "rotate-180" : ""}`} />
              </button>
              <AnimatePresence>
                {faqOpen[idx] && (
                  <motion.div
                    initial={{ height: 0 }}
                    animate={{ height: "auto" }}
                    exit={{ height: 0 }}
                    className="overflow-hidden"
                  >
                    <p className="px-5 pb-4 pt-1 text-xs text-[#7A6A5E] font-bold leading-relaxed border-t border-neutral-100 bg-[#FFF9F2]/30">
                      {item.a}
                    </p>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>
      </section>

      {/* --- FOOTER --- */}
      <footer className="border-t-4 border-[#3B2416] max-w-7xl mx-auto px-4 lg:px-8 pt-12 pb-6 mt-12 text-center flex flex-col items-center gap-4">
        <Image
          src="/illustrations/logo-petit-baobab.webp"
          alt="Petit Baobab"
          width={130}
          height={40}
          className="w-auto h-[40px] object-contain"
        />
        <p className="text-xs text-[#7A6A5E] font-bold max-w-md">
          {lang === "fr"
            ? "Petit Baobab Studio — Studio éducatif créatif pour éveiller l'imaginaire des enfants en Afrique de l'Ouest."
            : "Petit Baobab Studio — Creative educational studio to awaken children's imaginations in West Africa."}
        </p>
        <span className="text-[10px] font-semibold text-[#94A3B8] mt-4">
          © {new Date().getFullYear()} Petit Baobab. Tous droits réservés. Ouagadougou, Burkina Faso.
        </span>
      </footer>

    </div>
  )
}

// Wrap with custom mock Link in page structure if next/link import throws standard compiler error in Next config, 
// or define inline Link to handle anchor scrolling safely:
function Link({ href, children, ...props }: any) {
  const router = useRouter()
  const handleClick = (e: any) => {
    if (href.startsWith("#")) {
      e.preventDefault()
      const element = document.getElementById(href.slice(1))
      if (element) {
        element.scrollIntoView({ behavior: "smooth" })
      }
    } else {
      e.preventDefault()
      router.push(href)
    }
  }
  return (
    <a href={href} onClick={handleClick} {...props}>
      {children}
    </a>
  )
}
