export enum EventName {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  CREATE_DRAWING = 'CREATE_DRAWING',
  SAVE_DRAWING = 'SAVE_DRAWING',
  DELETE_DRAWING = 'DELETE_DRAWING',
  CREATE_BOOK = 'CREATE_BOOK',
  DOWNLOAD_BOOK = 'DOWNLOAD_BOOK',
  BUY_PRODUCT = 'BUY_PRODUCT',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  CREATE_STORY = 'CREATE_STORY',
  START_LEARNING_PATH = 'START_LEARNING_PATH',
  FINISH_LEARNING_PATH = 'FINISH_LEARNING_PATH',
  UNLOCK_BADGE = 'UNLOCK_BADGE',
  GAIN_XP = 'GAIN_XP',
  SPEND_STARS = 'SPEND_STARS',
  WATCH_STORY = 'WATCH_STORY',
  PLAY_GAME = 'PLAY_GAME',
  COMPLETE_GAME = 'COMPLETE_GAME',
  DOWNLOAD_CERTIFICATE = 'DOWNLOAD_CERTIFICATE',
  CREATE_PROJECT = 'CREATE_PROJECT'
}

export interface AnalyticsEvent {
  id?: string; // generated by DB
  account_id?: string | null;
  child_id?: string | null;
  school_id?: string | null;
  event_name: EventName;
  event_category?: string | null;
  resource_type?: string | null;
  resource_id?: string | null;
  metadata?: Record<string, any> | null;
  ip_country?: string | null;
  device?: string | null;
  platform?: string | null;
  created_at?: string;
}
